# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  mem_guard_config = debug
endif
ifeq ($(config),release)
  mem_guard_config = release
endif

PROJECTS := mem_guard

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

mem_guard:
ifneq (,$(mem_guard_config))
	@echo "==== Building mem_guard ($(mem_guard_config)) ===="
	@${MAKE} --no-print-directory -C . -f mem_guard.make config=$(mem_guard_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f mem_guard.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mem_guard"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"